name: foydali_nuqtalar_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #networking dependencies
  dio: ^5.4.1
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1

  #hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3

  #state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  rxdart: ^0.27.7

  #dependency injection
  get_it: ^7.6.7

  #system
  easy_localization: ^3.0.6
  flutter_localization: ^0.2.0
  permission_handler: ^11.3.0

  #pinput auth
  pinput: ^4.0.0
  smart_auth: ^2.0.0

  #for ui
  carousel_slider: ^4.2.1
  lottie: ^3.1.0
  google_fonts: 6.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/png/
     - assets/images/svg/
     - assets/translations/
